name: Publish to PyPI

on: workflow_dispatch

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:

      - name: Checkout
        uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d

      - name: Build .whl file  
        run: uv build

      - name: Publish to Pypi
        run: uv publish